### ISSUE TITLE
Dashboard import failing for OCP nightly version

### ISSUE THREAD

**Issue by bose-abhishek** [redhat-performance/odf-grafana#28]
As reported by the ODF QE team, dashboard import is failing for a recent OCP nightly version.

`TASK [dashboard : Wait for the API to provide a list of dashboards just uploaded] *********************************************************************************************************
Tuesday 17 September 2024  15:08:14 +0530 (0:00:00.009)       0:01:26.434 ***** `

**Comment by bose-abhishek** [comment]
Observing the error with GA version as well.
OCP v4.16.14

**Comment by bose-abhishek** [comment]
related upstream bug: https://github.com/grafana/grafana-operator/issues/1675

**Comment by sarahbx** [comment]
Hi @bose-abhishek, would you be able to test the change from
https://github.com/redhat-performance/odf-grafana/pull/29 ?

**Comment by bose-abhishek** [comment]
As #29 solves this issue and has been merged, so closing this issue.
